In [2]:
import pandas as pd
import numpy as np

In [6]:
# Load the dataset
df = pd.read_excel("zomato.csv-1.xlsx")

# Display first 5 rows
df.head()

,Unnamed: 0.1,Unnamed: 0,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
0,0,0,#FeelTheROLL,Quick Bites,3.4,7,200.0,No,No,Fast Food,Bellandur,Bellandur
1,1,1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,"Fast Food, Beverages","Byresandra,Tavarekere,Madiwala",HSR
2,2,2,#refuel,Cafe,3.7,37,400.0,Yes,No,"Cafe, Beverages",Bannerghatta Road,Bannerghatta Road
3,3,3,'@ Biryani Central,Casual Dining,2.7,135,550.0,Yes,No,"Biryani, Mughlai, Chinese",Marathahalli,Marathahalli
4,4,4,'@ The Bbq,Casual Dining,2.8,40,700.0,Yes,No,"BBQ, Continental, North Indian, Chinese, Bever...",Bellandur,Bellandur

In [7]:
# Display dataset information
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.info()

Rows: 7105
Columns: 12
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7105 entries, 0 to 7104
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0.1           7105 non-null   int64
 1   Unnamed: 0             7105 non-null   int64
 2   restaurant name        7105 non-null   object
 3   restaurant type        7105 non-null   object
 4   rate (out of 5)        7037 non-null   float64
 5   num of ratings         7105 non-null   int64
 6   avg cost (two people)  7048 non-null   float64
 7   online_order           7105 non-null   object
 8   table booking          7105 non-null   object
 9   cuisines type          7105 non-null   object
 10  area                   7105 non-null   object
 11  local address          7105 non-null   object
dtypes: float64(2), int64(3), object(7)
memory usage: 666.2+ KB

In [8]:
# Check missing values
df.isnull().sum()

Unnamed: 0.1              0
Unnamed: 0                0
restaurant name           0
restaurant type           0
rate (out of 5)          68
num of ratings            0
avg cost (two people)    57
online_order              0
table booking             0
cuisines type             0
area                      0
local address             0
dtype: int64

In [9]:
# Fill missing values in text columns with "Unknown"

df["restaurant type"] = df["restaurant type"].fillna("Unknown")
df["cuisines type"] = df["cuisines type"].fillna("Unknown")
df["local address"] = df["local address"].fillna("Unknown")

# Fill missing ratings with the average rating

df["rate (out of 5)"] = df["rate (out of 5)"].fillna(df["rate (out of 5)"].mean())

In [10]:
# Remove duplicate rows

df = df.drop_duplicates()

print("Remaining rows:", len(df))

Remaining rows: 7105

In [11]:
# Remove extra spaces and standardize text

text_columns = [
    "restaurant name",
    "restaurant type",
    "cuisines type",
    "area",
    "local address"
]

for col in text_columns:
    df[col] = df[col].astype(str).str.strip().str.title()

df["online_order"] = df["online_order"].astype(str).str.strip().str.lower()
df["table booking"] = df["table booking"].astype(str).str.strip().str.lower()

In [12]:
# Convert numeric columns

df["rate (out of 5)"] = pd.to_numeric(df["rate (out of 5)"], errors="coerce")

df["num of ratings"] = pd.to_numeric(df["num of ratings"], errors="coerce")

df["avg cost (two people)"] = pd.to_numeric(df["avg cost (two people)"], errors="coerce")

In [13]:
# Rename columns for consistency

df.rename(columns={
    "restaurant name":"restaurant_name",
    "restaurant type":"restaurant_type",
    "rate (out of 5)":"rating",
    "num of ratings":"num_ratings",
    "avg cost (two people)":"avg_cost_two_people",
    "table booking":"table_booking",
    "online_order":"online_order",
    "cuisines type":"cuisines_type",
    "local address":"local_address"
}, inplace=True)

In [14]:
# Create Rating Category

df["rating_category"] = np.where(
    df["rating"] >= 4,
    "Highly Rated",
    "Average Rated"
)

In [15]:
df.head()

,Unnamed: 0.1,Unnamed: 0,restaurant_name,restaurant_type,rating,num_ratings,avg_cost_two_people,online_order,table_booking,cuisines_type,area,local_address,rating_category
0,0,0,#Feeltheroll,Quick Bites,3.4,7,200.0,no,no,Fast Food,Bellandur,Bellandur,Average Rated
1,1,1,#L-81 Cafe,Quick Bites,3.9,48,400.0,yes,no,"Fast Food, Beverages","Byresandra,Tavarekere,Madiwala",Hsr,Average Rated
2,2,2,#Refuel,Cafe,3.7,37,400.0,yes,no,"Cafe, Beverages",Bannerghatta Road,Bannerghatta Road,Average Rated
3,3,3,'@ Biryani Central,Casual Dining,2.7,135,550.0,yes,no,"Biryani, Mughlai, Chinese",Marathahalli,Marathahalli,Average Rated
4,4,4,'@ The Bbq,Casual Dining,2.8,40,700.0,yes,no,"Bbq, Continental, North Indian, Chinese, Bever...",Bellandur,Bellandur,Average Rated

In [16]:
# Export cleaned dataset

df.to_csv("cleaned_dataset.csv", index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [17]:
from google.colab import files

files.download("cleaned_dataset.csv")